### PR TITLE
Renamed holoplot back to hvplot

### PR DESCRIPTION
**Pull request by philippjfr**
Due to trademark concerns we have decided to rename holoplot back to hvplot.

### CODE REVIEW

**Comment by stonebig** [comment]
a new hvplot wheel in next few minutes would be appreciated.

**Comment by stonebig** [comment]
pyviz would have been a good solution too, as the jupyterlab plugin is "jupyterlab_pyviz" already

**Comment by philippjfr** [comment]
We did consider that but PyViz is already used as the meta-package for all our work and also a unified repository for documentation on using all the tools together.

**Comment by stonebig** [comment]
pypi hvplot webpage doesn't exist yet.

**Comment by philippjfr** [comment]
Will be tagging a new release later today.

**Comment by philippjfr** [comment]
I've released 0.1.1 but there was an issue while uploading the package: https://travis-ci.org/pyviz/holoplot/jobs/398874596 Will try to resolve it tomorrow.

**Comment by stonebig** [comment]
ok.

**Pull request merged**
